// <auto-generated />
namespace SFC.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class DB_Alunos : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(DB_Alunos));
        
        string IMigrationMetadata.Id
        {
            get { return "201801051626305_DB_Alunos"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
